FINISH_SET_LOAN = 'finish_set_loan'
WAITING_START_NEW_GAME = 'WAITING_START_NEW_GAME'
WAITING_CHOOSE_LAND = 'waiting_choose_land'
WAITING_CHOOSE_PROBING_EQUIPMENT = 'waiting_choose_probing_equipment'
FINISH_WAITING_START = 'FINISH_WAITING_START'
FINISH_CHOOSE_LAND = 'finish_choose_land'
FINISH_CHOOSE_PROBING_EQUIPMENT = 'finish_choose_probing_equipment'